/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import DBconnect.Product;
import DBconnect.ProductController;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ngoc Nguyen
 */
public class OrderTable extends javax.swing.JFrame {

    /**
     * Creates new form OrderTable
     */
    public static DefaultTableModel modelorder,modelorder1,modelorder2,modelfindproduct;
    public OrderTable() {
        initComponents();
        setLocationRelativeTo(null);
        //set model tuừng bàn
        //Bàn 1
        modelorder = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
        modelorder.addColumn("Mã sản phẩm");
        modelorder.addColumn("Tên sản phẩm");
        modelorder.addColumn("Loại");
        modelorder.addColumn("Giá tiền");
        modelorder.addColumn("Số lượng");
        table_order.setModel(modelorder);
        //Bàn 2
        modelorder1 = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
        modelorder1.addColumn("Mã sản phẩm");
        modelorder1.addColumn("Tên sản phẩm");
        modelorder1.addColumn("Loại");
        modelorder1.addColumn("Giá tiền");
        modelorder1.addColumn("Số lượng");
        //bàn 3
        modelorder2 = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
        modelorder2.addColumn("Mã sản phẩm");
        modelorder2.addColumn("Tên sản phẩm");
        modelorder2.addColumn("Loại");
        modelorder2.addColumn("Giá tiền");
        modelorder2.addColumn("Số lượng");
        //---
        //model tìm kiếm
        modelfindproduct = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
        modelfindproduct.addColumn("IDProduct");
        modelfindproduct.addColumn("ProductName");
        modelfindproduct.addColumn("IDType");
        modelfindproduct.addColumn("Price");
    }
    //set modeltabble ((từng bàn)
    public void showproduct(String productnamefind){
        ArrayList<Product> list;
        list = ProductController.findProduct(productnamefind);
        for (Product product1:list){
            modelfindproduct.addRow(product1.toArray());
        } 
        table_findproduct.setModel(modelfindproduct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbb_table = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_order = new javax.swing.JTable();
        btn_order = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbb_idtype = new javax.swing.JComboBox<>();
        txt_idproduct = new javax.swing.JTextField();
        txt_productname = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spin_quantity = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        addorder = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_findproduct = new javax.swing.JTable();
        btn_findproduct = new javax.swing.JButton();
        txt_findproduct = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đặt bàn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        cbb_table.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giỏ hàng 1", "Giỏ hàng 2", "Giỏ Hàng 3" }));
        cbb_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_tableActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(table_order);

        btn_order.setText("Xuất hóa đơn");
        btn_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_orderActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Mã loại:");

        jLabel2.setText("Mã sản phẩm:");

        jLabel3.setText("Tên sản phẩm:");

        jLabel4.setText("Giá:");

        cbb_idtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T01", "T02", "T03", "T04", "T05", "T06", " " }));

        jLabel5.setText("đồng");

        spin_quantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel6.setText("Số lượng:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spin_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(cbb_idtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(94, 94, 94))
                        .addComponent(txt_idproduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_productname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(txt_price)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addGap(26, 26, 26))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbb_idtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_idproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spin_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        addorder.setText("Thêm");
        addorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addorderActionPerformed(evt);
            }
        });

        btn_remove.setText("Hủy sản phẩm");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        table_findproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_findproductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_findproduct);

        btn_findproduct.setText("Tìm");
        btn_findproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findproductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_findproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_findproduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbb_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btn_order)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addorder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_remove)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_order)
                    .addComponent(cbb_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_findproduct)
                    .addComponent(txt_findproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addorder)
                            .addComponent(btn_remove)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Japan Figure");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addorderActionPerformed
        //thêm sản phẩm order
        String idproduct = txt_idproduct.getText();
        String productname =txt_productname.getText();
        int price = Integer.parseInt(txt_price.getText());
        String idtype = (String) cbb_idtype.getSelectedItem();        
        String table = cbb_table.getSelectedItem().toString();
        int quantities = (int)spin_quantity.getValue();
        Product product2 = new Product(idproduct,productname,idtype,price,quantities);
        int rowcount = table_order.getRowCount();
        switch (table) {
            case "Bàn 2":
                //kiểm tra sản phẩm đã thêm thì set lại số lượng
                if(rowcount>0){
                    for(int i = 0;i<rowcount;i++){
                        if(idproduct.equals(modelorder1.getValueAt(i, 0)))
                        {
                            modelorder1.removeRow(i);
                            break;
                        }
                    }
                    modelorder1.addRow(product2.toArray2());
                    table_order.setModel(modelorder1);
                    break;
                }
                modelorder1.addRow(product2.toArray2());
                table_order.setModel(modelorder1);
                break;
                
            case "Bàn 3":
                 if(rowcount>0){
                    for(int i = 0;i<rowcount;i++){
                        if(idproduct.equals(modelorder2.getValueAt(i, 0)))
                        {
                            modelorder2.removeRow(i);
                            break;
                        }
                    }
                    modelorder2.addRow(product2.toArray2());
                    table_order.setModel(modelorder2);
                    break;
                }
                modelorder2.addRow(product2.toArray2());
                table_order.setModel(modelorder2);
                break;
            case "Bàn 1":
                 if(rowcount>0){
                    for(int i = 0;i<rowcount;i++){
                        if(idproduct.equals(modelorder.getValueAt(i, 0)))
                        {
                            modelorder.removeRow(i);
                            break;
                        }
                    }
                    modelorder.addRow(product2.toArray2());
                    table_order.setModel(modelorder);
                    break;
                }
                modelorder.addRow(product2.toArray2());
                table_order.setModel(modelorder);
                break;
        }
    }//GEN-LAST:event_addorderActionPerformed

    private void btn_findproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findproductActionPerformed
        //tìm sản phẩm theo tên
        String productnamefind = txt_findproduct.getText();
        showproduct(productnamefind);
    }//GEN-LAST:event_btn_findproductActionPerformed

    private void table_findproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_findproductMouseClicked
        //chuyển dữ liệu sang textbox...
        if(evt.getClickCount() == 2){
            int rowseleted = table_findproduct.getSelectedRow();
            txt_idproduct.setText((String)modelfindproduct.getValueAt(rowseleted, 0));
            cbb_idtype.setSelectedItem(modelfindproduct.getValueAt(rowseleted, 2));
            txt_productname.setText((String)modelfindproduct.getValueAt(rowseleted, 1));
            txt_price.setText(String.valueOf(modelfindproduct.getValueAt(rowseleted, 3)));
        }
    }//GEN-LAST:event_table_findproductMouseClicked

    private void cbb_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_tableActionPerformed
        //hiển thị table theo combobox bàn
        String table = cbb_table.getSelectedItem().toString();
        switch (table) {
            case "Bàn 2":
                modelorder1.fireTableDataChanged();
                table_order.setModel(modelorder1);
                break;
            case "Bàn 3":
                modelorder2.fireTableDataChanged();
                table_order.setModel(modelorder2);
                break;
            default:
                modelorder.fireTableDataChanged();
                table_order.setModel(modelorder);
                break;
        }
        
    }//GEN-LAST:event_cbb_tableActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        //chon bàn - xóa sản phẩm
        String table = cbb_table.getSelectedItem().toString();
        switch (table) {
            case "Bàn 2":
                removeproduct(modelorder1);
                modelorder1.fireTableDataChanged();
                table_order.setModel(modelorder1);
                break;
            case "Bàn 3":
                removeproduct(modelorder2);
                modelorder2.fireTableDataChanged();
                table_order.setModel(modelorder2);
                break;
            default:
                removeproduct(modelorder);
                modelorder.fireTableDataChanged();
                table_order.setModel(modelorder);
                break;
        }
    }//GEN-LAST:event_btn_removeActionPerformed
     public void removeproduct(DefaultTableModel model){
        //xóa model tạo dòng đã chọn
        if(table_order.getSelectedRowCount() == 0)
        {
            JOptionPane.showMessageDialog(null, "Không xác định được sản phẩm cần hủy!!","Lỗi",JOptionPane.ERROR_MESSAGE);
        }else{
            model.removeRow(table_order.getSelectedRow());
        }
    }
    private void btn_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_orderActionPerformed
        File file;
        FileOutputStream fos;
        String text = "";
        float giatien = 0;
        int countRow = table_order.getRowCount();
        for(int i = 0 ; i< countRow ; i++){
            text = text+"Tên sản phẩm: "+table_order.getValueAt(i, 1)+"\t Giá:"+table_order.getValueAt(i,3) +"\r\n";
            giatien = giatien + (int)(table_order.getValueAt(i, 3));
        }
        text =cbb_table.getSelectedItem()+"\r\n"+ text +"Tổng tiền: \t"+ giatien;
        try{
           file = new File("E:\\new.txt");
           fos = new FileOutputStream(file);
           if(!file.exists()){
               file.createNewFile();
           }
           byte[] contentInBytes = text.getBytes();
           fos.write(contentInBytes);
           fos.flush();
           fos.close();
           JOptionPane.showMessageDialog(null, "Thành công!!","thông báo",JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_orderActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addorder;
    private javax.swing.JButton btn_findproduct;
    private javax.swing.JButton btn_order;
    private javax.swing.JButton btn_remove;
    private javax.swing.JComboBox<String> cbb_idtype;
    private javax.swing.JComboBox<String> cbb_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spin_quantity;
    private javax.swing.JTable table_findproduct;
    private javax.swing.JTable table_order;
    private javax.swing.JTextField txt_findproduct;
    private javax.swing.JTextField txt_idproduct;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_productname;
    // End of variables declaration//GEN-END:variables
}
